---
- hosts: all
  roles:
    - role: jdauphant.nginx
      nginx_http_params:
        - sendfile on
        - access_log /var/log/nginx/access.log
      nginx_sites:
         phoenix:
           - listen 80
           - server_name _
           - root /var/www/phoenix.com/_site
           - location / { try_files $uri $uri/ /index.html; }
