---
  - hosts: loadbalancer
    remote_user: root
    become: true
    tasks:
      - service: name=nginx state=stopped

  - hosts: webserver
    remote_user: root
    become: true
    tasks:
      - service: name=apache2 state=stopped

  - hosts: database
    remote_user: root
    become: true
    tasks:
      - service: name=mysql state=restarted

    - hosts: loadbalancer
      remote_user: root
      become: true
      tasks:
        - service: name=nginx state=started

    - hosts: webserver
      remote_user: root
      become: true
      tasks:
        - service: name=apache2 state=started
